[build]
  # Specify the build directory
  publish = "client/build"
  
  # Build command - only build the client React app
  command = "cd client && npm install && npm run build"
  
  # Ignore Python files - they are not needed for this deployment
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)requirements.txt' ':(exclude)streamlit_app.py' ':(exclude)server/'"

[build.environment]
  # Specify Node.js version to avoid compatibility issues
  NODE_VERSION = "20"
  
  # Disable Python builds completely
  PYTHON_VERSION = ""
  # Skip Python dependency installation
  SKIP_PYTHON_INSTALL = "true"
  # Disable automatic dependency detection
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect API calls to your backend (if you deploy it separately)
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-backend-url.com/api/:splat"
#   status = 200
#   force = true

# Headers for HTML pages - less restrictive to allow text input
[[headers]]
  for = "/*"
  [headers.values]
    # Microphone permissions for audio recording
    Permissions-Policy = "microphone=(self), camera=(self)"
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Content Security Policy - allow inline scripts and styles for React
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://promptlingo-backend.onrender.com https://*.onrender.com; media-src 'self' blob: data:;"

# Stricter headers for WASM files only
[[headers]]
  for = "*.wasm"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Embedder-Policy = "require-corp"
    Content-Type = "application/wasm"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/wasm/*"
  [headers.values]
    Cross-Origin-Resource-Policy = "cross-origin"

# SPA fallback - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
